---
- name: add nginx/stable repo
  apt_repository:
      repo: ppa:nginx/stable
      update_cache: yes
  sudo: yes
  
- name: install nginx
  sudo: yes
  apt: name=nginx update_cache=yes cache_valid_time=86400
  
# - name: download the config file
#   fetch: src=/etc/nginx/nginx.conf dest={{ role_path }}/templates/
#   sudo: yes

- name: add nginx config file
  sudo: yes
  template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf

# - name: add fastcgi_params file
#   sudo: yes
#   template:
#       src: fastcgi.conf.j2
#       dest: /etc/nginx/fastcgi_params

- name: enable default site
  file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link
  sudo: yes
  when: not disable_default

- name: disable default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  sudo: yes
  when: disable_default