---
- name: enable IPv4 port forwarding in configuration file
  lineinfile:
      dest: /etc/sysctl.conf
      regexp: 'net\.ipv4\.ip_forward'
      line: net.ipv4.ip_forward=1
  sudo: yes
  
- name: rerun sysctl with new configuration
  command: sysctl -p /etc/sysctl.conf
  sudo: yes